# Each entry is (setup/question, punchline/answer).
# Add your own! Batch runs hand these out in order, so no two posts share one
# until the list runs out.

JOKES = [
    ("Why did the lipstick break up with the mirror?", "It needed space to reflect."),
    ("Why don't skeletons fight each other?", "They don't have the guts."),
    ("What do you call a fake noodle?", "An impasta."),
    ("Why did the scarecrow win an award?", "He was outstanding in his field."),
    ("What did one wall say to the other?", "I'll meet you at the corner."),
    ("Why can't a bicycle stand up by itself?", "It's two tired."),
    ("What do you call a bear with no teeth?", "A gummy bear."),
    ("Why did the cookie go to the doctor?", "It was feeling crummy."),
    ("What did the lip balm say to dry lips?", "Don't worry, I've got you covered."),
    ("Why are lips so good at keeping secrets?", "They're always sealed."),
    ("What do you call a sleeping bull?", "A bulldozer."),
    ("Why did the coffee file a police report?", "It got mugged."),
    ("What did the ocean say to the beach?", "Nothing, it just waved."),
    ("Why don't eggs tell jokes?", "They'd crack each other up."),
    ("Why did the moisturizer go to therapy?", "It had too many dry spells."),
    ("What did the serum say to the wrinkle?", "Smooth move."),
    ("Why did the nail polish get promoted?", "It always nailed it."),
    ("Why was the shampoo so calm?", "It knew how to lather, rinse, repeat."),
    ("What's a perfume's favourite kind of music?", "Anything with good notes."),
    ("Why did the blush go to the party?", "To get a little cheeky."),
    ("What did the concealer say at the meeting?", "Let's cover the basics."),
    ("Why did the hair dryer get a raise?", "It always blew everyone away."),
    ("Why was the face mask so relaxed?", "It knew how to unwind for 15 minutes."),
    ("What did the sunscreen say to the sun?", "Not today."),
    ("Why did the eyeliner get top marks?", "It always stayed on the line."),
    ("What do you call a dinosaur with great skin?", "A glow-saurus."),
    ("Why did the toner quit its job?", "It wanted a fresh start."),
    ("Why don't hair oils ever argue?", "They just smooth things over."),
    ("What did the cleanser say to the dirt?", "It's not you, it's me... actually, it's you."),
    ("Why did the lip gloss win the race?", "It had a shiny finish."),
    ("What's a brow's favourite exercise?", "Raises."),
    ("Why was the dry shampoo so popular?", "It always showed up when you needed a refresh."),
    ("What did the powder say to the shine?", "You've been set."),
    ("Why did the body scrub get invited everywhere?", "It was so smooth."),
    ("Why do candles make terrible friends?", "They burn you and then go out."),
    ("What did the left eye say to the right eye?", "Between you and me, something smells."),
    ("Why did the math book look sad?", "It had too many problems."),
    ("What do you call cheese that isn't yours?", "Nacho cheese."),
    ("Why did the tomato blush?", "It saw the salad dressing."),
    ("Why did the golfer bring two pairs of pants?", "In case he got a hole in one."),
    ("What do you call a pile of cats?", "A meowtain."),
    ("Why did the bee get married?", "He found his honey."),
    ("What did the honey hair oil say to frizz?", "Bee gone."),
    ("Why did the vanilla perfume get a compliment?", "It was simply sweet."),
]

RIDDLES = [
    ("What has keys but can't open locks?", "A piano."),
    ("What gets wetter the more it dries?", "A towel."),
    ("What has hands but can't clap?", "A clock."),
    ("What can you catch but not throw?", "A cold."),
    ("What has a neck but no head?", "A bottle."),
    ("What goes up but never comes down?", "Your age."),
    ("What has one eye but can't see?", "A needle."),
    ("The more you take, the more you leave behind. What are they?", "Footsteps."),
    ("What belongs to you, but others use it more than you do?", "Your name."),
    ("What is always in front of you but can't be seen?", "The future."),
    ("I have a cap but no head, I come in many shades, and I love a kiss. What am I?", "A lipstick!"),
    ("What has many teeth but can't bite?", "A comb."),
    ("What can fill a room but takes up no space?", "Light."),
    ("What has words but never speaks?", "A book."),
    ("What runs but never walks?", "Water."),
    ("What has a face and two hands but no arms or legs?", "A clock."),
    ("What can you hold without touching it?", "Your breath."),
    ("What gets bigger the more you take away?", "A hole."),
    ("What has a thumb and four fingers but isn't alive?", "A glove."),
    ("What can travel around the world while staying in a corner?", "A stamp."),
    ("What is full of holes but still holds water?", "A sponge."),
    ("What has legs but doesn't walk?", "A table."),
    ("What comes once in a minute, twice in a moment, but never in a thousand years?", "The letter M."),
    ("What has a head and a tail but no body?", "A coin."),
    ("What can you break without touching it?", "A promise."),
    ("What shows your face but has no face of its own?", "A mirror."),
    ("I'm tall when I'm young and short when I'm old. What am I?", "A candle."),
    ("What has a bottom at the top?", "Your legs."),
    ("What kind of room has no doors or windows?", "A mushroom."),
    ("What begins with T, ends with T, and has T in it?", "A teapot."),
    ("What has to be broken before you can use it?", "An egg."),
    ("What do you smell but can never see, and can wear but never touch?", "Perfume."),
    ("I keep your hair in place but I'm not a hat. What am I?", "Hairspray."),
    ("I hide spots and dark circles but I'm not a magician. What am I?", "Concealer."),
    ("I'm a bit of glass full of mist, one spray and you smell like a holiday. What am I?", "A body mist."),
    ("I'm worn on the face at night and peeled off in the morning. What am I?", "A sheet mask."),
    ("I come in a bottle, I'm painted on, and I dry on your fingertips. What am I?", "Nail polish."),
    ("I protect you every day, but you can't see me once I'm on. What am I?", "Sunscreen."),
    ("I go on wet hair and make it shine without a single drop of water. What am I?", "Hair oil."),
    ("I'm pressed in a compact and I make your skin glow. What am I?", "Highlighter."),
    ("What has roots that nobody sees, and is taller than trees?", "A mountain."),
    ("What five-letter word becomes shorter when you add two letters?", "Short."),
    ("Which month has 28 days?", "All of them."),
    ("What goes through cities and fields but never moves?", "A road."),
]
